#!/bin/sh
#

GIT_DIR="$PWD"
REPO="$(basename $GIT_DIR)"
TARGET_DIR="/srv/deploy/$REPO"

while read oldrev newrev ref
do
	if [ "$ref" = 'refs/heads/master' ];
	then
		echo "Deploying $newrev..."
		mkdir -p "$TARGET_DIR"
		git "--work-tree=$TARGET_DIR" "--git-dir=$GIT_DIR" checkout -f "$newrev" -q
		curl -v -s --unix-socket '/tmp/gitdeploy-master.sock' "http:/$REPO"
		echo "Deploy completed"
	fi
done
